version: "3.9"  
services:
  app:
    container_name: crafty
    restart: always
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - logvolume01:/var/log
volumes:
  logvolume01: {}